# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/data-pipeline-generator',
                'doc_host': 'https://josephmachado.github.io',
                'git_url': 'https://github.com/josephmachado/data-pipeline-generator',
                'lib_path': 'data_pipeline_generator'},
  'syms': { 'data_pipeline_generator.core': { 'data_pipeline_generator.core.foo': ('core.html#foo', 'data_pipeline_generator/core.py'),
                                              'data_pipeline_generator.core.say_hello': ( 'core.html#say_hello',
                                                                                          'data_pipeline_generator/core.py')}}}
